:revdate: {docdate}
:version-label!:
:sectnums:
:sectnumlevels: 5
:chapter-label: Introduction
:source-highlighter: rouge

## Introduction

The development of this Explainer is ongoing. This Explainer accompanies Version 0.8 of the Technical Specifications. 

This Explainer accompanies the draft of the C2PA Specifications with the intent of providing further background and clarification on the development of the standard, its goals, mechanisms and guidelines.

This Explainer is not a technical document and is directed towards the general public.


## Goals and Non-goals

The goal of the C2PA specifications is to tackle the extraordinary challenge of trusting media in a context of rapidly evolving technology and the democratization of powerful creation and editing techniques. To this end, the specifications are designed to enable global, opt-in, adoption of digital provenance techniques through the creation of a rich ecosystem of digital provenance enabled applications for a wide range of individuals and organizations while meeting appropriate security and privacy requirements, as well as human rights considerations.

It is important to highlight that C2PA specifications do not provide value judgments about whether a given set of provenance data is 'true', but instead merely whether the provenance information can be verified as associated with the underlying asset, correctly formed, and free from tampering. 


## Fundamentals (FAQs)

###  What does "Provenance" mean in the C2PA Specifications?
Provenance generally refers to the facts about the history of a piece of digital content assets (image, video, audio recording, document). C2PA enables the authors of provenance data to securely bind statements of provenance data to instances of content using their unique credentials. These provenance statements are called assertions by the C2PA. They may include assertions about who created the content and how, when, and where it was created. They may also include assertions about when and how it was edited throughout its life. The content author, and publisher (if authoring provenance data) always has control over whether to include provenance data as well as what assertions are included, such as whether to include identifying information (in order to allow for anonymous or pseudonymous assets). Included assertions can be removed in later edits without invalidating or removing all of the included provenance data in a process called xref:_what_is_redaction_and_how_does_it_work[redaction]. 


### How is trust in digital assets established?
In the C2PA Specifications, trust decisions are made by the consumer of the asset based on the identity of the actor(s) who signed the provenance data along with the information in the assertions contained in the provenance. This signing takes place at each significant moment in an asset's life (e.g., creation, editing, etc.) through the use of the actor's unique credentials and ensures that the provenance data remains cryptographically bound to the newly created or updated asset.

### What does it mean that provenance data is cryptographically bound to the asset?
The provenance data and the asset are the two parts of the same puzzle - a unique puzzle. The possibility of any other pieces ever matching, either by coincidence or by purposeful creation, is so low that it would be practically impossible. This is known as a hard binding. 

In other words, any alteration to either the asset or the provenance, however insignificant, would alter the mathematical algorithm - the shape of the piece of the puzzle – in such a way that they would no longer match. 

For more technical information on this see "Hard binding" in the https://c2pa.org/public-draft/#_glossary[glossary] and the [non-normative guidelines].


### Can C2PA help with assets created from multiple sources?
When one asset is created from a series of other assets, those sources are referred to as the ingredients. Each ingredient that is used in the final (composed) asset can be identified as part of the final provenance, including the addition of the provenance of each individual ingredient.


### What is redaction and how does it work?
Redaction is the process of permanently removing information - in the world of C2PA it specifically refers to removing assertions. 

For example, if a human rights organization wishes to remove from an image assertions about the photographer, it can do so via the redaction process. In addition, they could, at the same time, add more information about the time and location of where the image was taken. The act of redaction (and possibly adding addition information) becomes part of the provenance of the asset.

### TODO
[NOTE]
====
Some of the additional areas that information will be provide about include:
- Synthetic content
- Privacy
- Guarantees C2PA is providing the consumer
- Who can be / Process of becoming a signer (signing entities)
- Discussion of how provenance does not have to include everything from the origin to current due to the Trust Model.
====

