@startuml Example_Manifest

    ' allows mixing various objects in a single diagram
    allow_mixing

    ' hide the spot
    ' hide any empty things...
    hide circle
    hide empty members

    ' styling
    skinparam componentStyle rectangle
    left to right direction

    frame cacb as "Manifest Block (`cacb`)" {
        rectangle JMB [
            {{json
                {
                "label" : "c2pa"
                }
            }}
        ]

        frame cast as "Manifest (`cast`)" {
            rectangle JM [
                {{json
                    {
                    "label" : "joe-ed:urn:uuid:ABCD"
                    }
                }}
            ]

            frame caas as "Assertion Store Block (`caas`)" {
                frame "stds.schema-org.CreativeWork" {
                    rectangle JA1 [
                        {{json
                            {
                            "label" : "stds.schema-org.CreativeWork",
                            "content type" : "CBOR"
                            }
                        }}
                    ]
                    rectangle A1 [
                        <code>
                        {
                            "@context": "http://schema.org/",
                            "@type": "CreativeWork",
                            "datePublished": "2021-05-20T23:02:36+00:00",
                            "publisher": {
                                "name": "BBC News",
                                "publishingPrinciples": "https://www.bbc.co.uk/news/help-41670342",
                                "logo": "https://m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/5.1.0/bbc_news_logo.png",
                                "parentOrganization": {
                                    "name": "BBC",
                                    "legalName": "British Broadcasting Corporation"
                                }
                            }
                        }
                        </code>
                    ]
        
                    JA1 -[hidden]right-> A1
                }

                frame "c2pa.thumbnail.claim_0.png" {
                    rectangle JA2 [
                        {{json
                            {
                            "label" : "c2pa.thumbnail.claim_0.png",
                            "content type" : "embedded file",
                            "media type" : "image/png"
                            }
                        }}
                    ]
                    rectangle A2 [
                        <&image> Binary Image Data
                    ]

                    JA2 -[hidden]right-> A2
                }

                frame "c2pa.hash.data" {
                    rectangle JA3 [
                        {{json
                            {
                            "label" : "c2pa.hash.data",
                            "content type" : "CBOR"
                            }
                        }}
                    ]
                    rectangle A3 [
                        <code>
                            {
                                "exclusions": [ 
                                {
                                    "start": 9960,
                                    "length": 4213
                                } 
                                ],
                                "name": "Image content",
                                "alg" : "sha256",
                                "hash": b64'Auxjtmax46cC2N3Y9aFmBO9Jfay8LEwJWzBUtZ0sUM8gA=',
                                "pad" : "       "
                            }
                        </code>
                    ]

                    JA3 -[hidden]right-> A3
                }

                ' "stds.schema-org.CreativeWork" -down[hidden]-> "c2pa.thumbnail.claim_0.png"
                ' "c2pa.thumbnail.claim_0.png" -down[hidden]-> "c2pa.hash.data"
            }

            frame cacl as "Claim (`cacl`)" {
                rectangle JC [
                    {{json
                        {
                        "label" : "c2pa.claim",
                        "content type" : "CBOR"
                        }
                    }}
                ]
                rectangle C [
                    <code>
                        {
                            "claim_generator": "Joe's Photo Editor/2.0 (Windows 10)",
                            "signature" : 32("self#jumbf=c2pa/joe-ed:urn:uuid:ABCD/c2pa.signature"),
                            "assertions" : [
                                {
                                "url": 32("self#jumbf=c2pa/joe-ed:urn:uuid:ABCD/c2pa.assertions/c2pa.hash.data"),
                                "hash": b64'Auxjtmax46cC2N3Y9aFmBO9Jfay8LEwJWzBUtZ0sUM8gA'
                                },
                                {
                                "url": 32("self#jumbf=c2pa/joe-ed:urn:uuid:ABCD/c2pa.assertions/c2pa.thumbnail.claim.jpeg"),
                                "hash": b64'DjZifCgG2iKxcYeChKTOcWlJ9I/UC9/c5XFiJREqJFpwA='
                                },
                                {
                                "url": 32("self#jumbf=c2pa/joe-ed:urn:uuid:ABCD/c2pa.assertions/stds.schema-org.CreativeWork"),
                                "hash": b64'm7ZifCgG2iKxcYeChKTOcWlJ9I/UC9/c5XFiJREqJFpwA='
                                }
                            ],
                        }
                    </code>
                ]

                JC -[hidden]right-> C
            }

            frame casg as "Claim Signature (`casg`)" {
                rectangle JCS [
                    {{json
                        {
                        "label" : "c2pa.signature",
                        "content type" : "CBOR"
                        }
                    }}
                ]
                rectangle CS [
                    <code>
                        98(
                            [
                                {
                                    / protected / h'', 
                                    / unprotected / {}, 
                                    / payload / null, 
                                    / signatures / [
                                        [
                                            / protected / <<{1:-39}>>, 
                                            / alg / PS512,
                                            / unprotected / {
                                                / kid / 4:'11'
                                            }, 
                                            / signature / h'e2aeafd40d69d19dfe6e52077c5d7ff4e408282cbefb5d06cbf414af2e19d982ac45ac98b8544c908b4507de1e90b717c3d34816fe926a2b98f53afd2fa0f30a'
                                        ],
                                    ],
                                }
                            ],
                        )
                    </code>
                ]

                JCS -[hidden]right-> CS
            }


            JM -[hidden]right-> caas
            caas -[hidden]right-> cacl
            cacl -[hidden]right-> casg
        }

        JMB -[hidden]right-> cast
    }

@enduml
