@startuml Photo_Manifest

    ' allows mixing various objects in a single diagram
    allow_mixing

    ' hide the spot
    ' hide any empty things...
    hide circle
    hide empty members

    ' styling
    skinparam componentStyle rectangle
    'left to right direction

	skinparam FrameBackgroundColor<<casg>> Magenta
	skinparam FrameBackgroundColor<<Claim Signature>> Magenta

    frame cacb as "Manifest Store" {
        frame cast as "Manifest" {
            frame caas as "Assertion Store" {
                frame "stds.exif" {
                    rectangle A1 [
                        <&code>
						JSON-LD structure with
						details such as the camera
						used to take the photo
                    ]
                }

                frame "c2pa.thumbnail.claim_0.png" {
                    rectangle A2 [
                        <&image> Binary Image Data
                    ]
                }

                frame "c2pa.hash.data" {
                    rectangle A3 [
                        <&code>
						CBOR structure containing
						information about the
						cryptographic hashes binding
						to the content.
                    ]
                }
            }

            frame cacl as "Claim" {
                rectangle C [
                    <&code>
					CBOR structure with
					references to the Assertions
					and the Claim Signature
                ]
            }

            frame casg as "Claim Signature" {
                rectangle CS [
					<&key> COSE Digital Signature
                ]
            }

			caas -[hidden]down-> cacl
            'cacl -[hidden]right-> caas
            cacl -[hidden]right-> casg
        }
    }

@enduml
