:revdate: {docdate}
:version-label!:
:sectnums:
:sectnumlevels: 5
:chapter-label: Trust Model
:source-highlighter: rouge

## Trust

### Cryptography

[NOTE]
.Items for future guidance
====
====


### Digital Signatures

==== Revocation Information

C2PA strongly recommends that claim generators retrieve and attach credential freshness information at signing time. This information should be added into the COSE signature as described in the specification.

NOTE: Attaching freshness information to the signature allows validators to conclude the manifest is still valid a) even if the signing credential has since expired or been revoked and b) without the need of an online query. 


==== Protecting claim signing keys

In practice, C2PA claim signing keys will be issued to systems that perform claim signing operations. These systems may make these operations available to end users and/or be deployed to user-owned platforms (e.g., mobile phones).  Issuance or disclosure of claim signing keys to malicious actors enables attackers to create claim signatures on arbitrary assets using the compromised identity. The resulting manifests are valid in terms of the C2PA specification, but effectively allow for spoofing provenance.

It is therefore important that systems that manage C2PA claim signing keys adhere to security and key management best practices. This includes leveraging platform-specific features (e.g., hardware security modules and cloud key management services), minimizing key reuse, and revoking keys when compromise is suspected. For more information on key management, see the https://csrc.nist.gov/Projects/Key-Management/Key-Management-Guidelines[NIST Key Management Guidelines].

===== Securing claim generation and signing operations

Some C2PA claim generation and signing systems may be exposed to untrusted users. Exploitation or misuse of these systems may allow attackers to create claim signatures on arbitrary assets using identities provided by the system. The resulting manifests are valid in terms of the C2PA specification, but effectively allow for spoofing provenance. The impact of such an attack may be amplified if identities are shared between users, and/or if the attack goes undetected for an extended period of time.

C2PA claim generation and signing systems should consider industry best practices for information security, secure development and operation, and anti-abuse practices, including leveraging available platform-specific features for deployment (e.g.,  link:https://developer.android.com/training/safetynet[Android SafetyNet], link:https://developer.apple.com/documentation/devicecheck[Apple DeviceCheck and AppAttest]).

#### Use of Self-Signed Certificates

[NOTE]
.Items for future guidance
====
====

### Trust Model

#### Trust Lists

The C2PA does not mandate the use of any specific "list of certificates or CAs that can be used to verify the trustworthiness of the signer of a manifest". There exists a variety of complexities in choosing the membership for such a list, and implementers should understand them prior to the creation of their list. The C2PA will continue to improve their guidance in this matter as the ecosystem grows.

[NOTE]
.Items for future guidance
====
Include information about creating, managing, using, etc.

* Multiple lists
* Managing the "private list" (security and general operational considerations)
====
