:revdate: {docdate}
:version-label!:
:sectnums:
:sectnumlevels: 5
:chapter-label: Validation
:source-highlighter: rouge

## Validation

=== Validation security practices

Special care should be taken when implementing validators. Like other software that processes untrusted input, validators may be the target of memory safety attacks, parser attacks, request forgery attacks against adjacent systems (e.g., when retrieving remote content or decoupled manifests), information leaks (e.g., via OCSP queries), denial of service attacks, and so on. Thus, it is important that these validators adhere to secure development and operations practices associated with their respective execution environment.

A manifest consumer that is performing validation (e.g., a web browser) may detect and mitigate attempted compromise of C2PA manifests or even the complete removal of C2PA manifests. It is recommended that manifest consumers consider forthcoming C2PA User Experience guidance, retrieval of decoupled manifests via xref:_guidance_on_use_of_soft_bindings[soft bindings] when appropriate, and other forthcoming C2PA recommendations to mitigate the impact of these types of attacks.

