This section documents information security threats to C2PA technology.  Threats are described as threat scenarios and organized by categorically by prospective attacker goals. Where an attacker goal is what the attacker is trying to achieve, or the desired outcome of the threat scenario.

Each threat scenarios is described as follows:

* Description: A short description of the threat scenario
* Prerequisites: Relevant requirements for attempting an attack or threat scenario
* Impact analysis: Summary of the impact of the threat scenario on the C2PA security model
* Guidance: Any supplementary security guidance on addressing the threat scenario or treating potential residual security risk

Note that this document refers to threat sources, agents, actors and other malicious entities commonly as attackers.

=== Threat and attack assumptions

The following assumptions are made about entities that may attack C2PA technology: 

* Attackers have full access to public assets and associated public metadata, including C2PA manifests.
* Attackers may attempt to access to claim generator software (e.g. C2PA-enabled photo editing software) as a typical user.
* Attackers do not have access to private keys referenced within the C2PA ecosystem (e.g. claim signing private keys, Timestamping Authority private keys, etc.). They may, however, attempt to access these keys via exploitation techniques.
* Attackers have the ability to publish assets to an impactful audience, e.g. as a social media user.
* Quantum computing cryptanalytic attacks are considered out-of-scope.

The following additional assumptions are made about the threat model:

* Attacks that rely on bypassing conventional security models of non-C2PA technology are considered out-of-scope. For example:
** Attacks against the C2PA Validator as an architectural component within a user agent (e.g. web browser) are considered in-scope. 
** A compromise of the C2PA validation logic via some non-C2PA attack vector within the user agent is considered out-of-scope, since this would typically require bypassing the security model of the user agent (e.g. escaping a web browser sandbox or compromising the host via other means).
* Attacks across conventional trust boundaries are considered in-scope.
** For example, attacks against C2PA-enabled assets traversing the internet.

=== Threats

==== Goal: Degrading access to provenance information

Threat scenarios in this category aim to prevent media consumers from reasoning about the provenance of assets. In terms of the security model, this is a compromise of availability of C2PA provenance data.

===== Threat: Stripping C2PA manifests

====== Description

An attacker removes C2PA manifests from an asset delivered with hard bindings.  For example, by downloading C2PA-enabled media from a social media site, stripping the C2PA manifest(s), and re-posting it.

====== Prerequisites

Technical ability to strip provenance data from published or stored assets and deliver the stripped assets targeted users or systems.  For example, via republishing to social media or on-path attacks.

====== Impact analysis

It is possible for an attacker to remove metadata as described. Depending on the context, this could cause a user agent not to display provenance information associated with the asset.

====== Security guidance

The impact of this threat scenario could be mitigated through use of decoupled manifests, e.g. by making decoupled C2PA manifests available to user agents when embedded manifests could be missing.

Use of decoupled manifests can introduce security and privacy issues. See the xref:_content_binding_security[Content binding security section] for more information.

===== Threat: Stripping from data within C2PA manifests

====== Description

An attacker removes metadata from within C2PA manifests(s) stored in a asset delivered with hard bindings, such as the assertion store, individual assertions, claims, claim signatures, etc. For example, by downloading C2PA-enabled media from a social media site, stripping the target C2PA metadata, and re-posting it.

====== Prerequisites

Technical ability to strip provenance data from published or stored assets and deliver the stripped assets targeted users or systems.  For example, via republishing to social media or on-path attacks.

====== Impact analysis

It is possible for an attacker to remove metadata as described. However, https://c2pa.org/public-draft/#_validation[validation checks] (e.g. as implemented by a user agent) will detect removal or partial removal of metadata stored within C2PA manifests. Removal of an entire C2PA manifest is possible, and described as a xref:_threat_stripping_c2pa_manifests[distinct threat scenario].

This is similar to the case of stripping all C2PA metadata. However, in this scenario there is an added benefit that user agents can explicitly detect the attempt to remove metadata as part of the validation process.

====== Security guidance

The impact of this threat scenario could be mitigated through explicit detection of missing metadata as described here, and factoring this into system behavior. For example, a user agent may modify display of the affected asset.

The impact of this threat scenario could be also mitigated through use of decoupled manifests, e.g. by making decoupled C2PA manifests available to user agents when embedded metadata is missing.

Use of decoupled manifests can introduce security and privacy issues. See the xref:_content_binding_security[Content binding security section] for more information.

==== Goal: Tamper with provenance information

Threat scenarios in this category aim to modify or spoof provenance information associated with C2PA-enabled assets, e.g. to present misleading provenance data to media consumers. This is considered a compromise of integrity of provenance data in terms of the C2PA security model.

===== Threat: Copying C2PA metadata

====== Description

An attacker copies valid, hard-bound C2PA metadata, such as assertions, claims, or entire C2PA manifests, from one C2PA-enabled asset to another.

====== Prerequisites

Technical ability to strip provenance data from published or stored assets and deliver the stripped assets targeted users or systems.  For example, via republishing to social media or on-path attacks.

====== Impact analysis

An attacker is able to perform the copying as described. However, C2PA hard bindings provide a cryptographic binding between assets and C2PA manifests via claim signatures. Thus, https://c2pa.org/public-draft/#_validation[validation checks] (e.g. as implemented by a user agent) will detect the replaced C2PA manifests.

This is similar to the case of stripping all C2PA metadata. However, in this scenario there is an added benefit that user agents can explicitly detect the attempt to remove metadata as part of the validation process.

====== Security guidance

The impact of this threat scenario could be mitigated through explicit detection of incorrect metadata as described here, and factoring this into system behavior.  For example, a user agent may modify display of the affected asset.

The impact of this threat scenario could also be mitigated through use of decoupled manifests, e.g. by making decoupled C2PA manifests available to user agents when metadata fails validation.

Use of decoupled manifests can introduce security and privacy issues. See the xref:_content_binding_security[Content binding security section] for more information.

===== Threat: Spoofing signed C2PA metadata via stolen key

====== Description

An attacker compromises the confidentiality of a claim signing key and uses it to attach valid, malicious provenance to a asset.

====== Prerequisites

Ability to read and use a valid C2PA claim signing key. For example by stealing it from a claim generation and signing system. Ability to copy, modify, or generate assets, add desired (valid) C2PA provenance metadata to them, and deliver them to targeted users or systems. For example, via republishing to social media or on-path attacks.

====== Impact analysis

An attacker that is able to steal a signing key can spoof valid C2PA manifests on arbitrary assets. This applies to both hard and soft bindings. Valid claim signatures will be limited to the exposed key; an attacker cannot impersonate other signers in this scenario. These manifests will pass validation checks.  Further, an attacker will be able to continue to generate assets with spoofed provenance until the compromised credential is revoked, and revocation status is propagated to the targeted users/systems.

If the signer’s credential type does not support or provide a means for revocation, it may be necessary to remove the trust anchor associated with the signer’s credential from the respective C2PA trust list to effectively revoke the malicious manifests. In this case, all manifests associated with the trust anchor will be invalidated.

Revocation of the signing key associated with the malicious manifests may invalidate other manifests if signing keys are reused between claim generation / claim signing system users.

====== Security guidance

Claim generators must adhere to best practices for securing keys in their respective operating environments. This includes using platform-specific best practices for key storage and management (e.g. hardware security modules, key management services), minimizing key reuse, and revoking keys when compromise is suspected. For more information on key management, see the https://csrc.nist.gov/Projects/Key-Management/Key-Management-Guidelines[NIST Key Management Guidelines].

It is highly recommended that all signing credentials include revocation information.

===== Threat: Spoofing signed C2PA metadata via misuse of claim generator

====== Description

An attacker misuses a legitimate claim generator (e.g. photo editing service) to add misleading provenance to a C2PA-enabled asset.

====== Prerequisites

Ability to access and exploit or misuse a claim generator system. For example, misuse of a claim generator may result in malicious additions of C2PA manifests or Claims to assets; exploitation of vulnerabilities in claim generators may lead to modification or tampering with existing C2PA manifest data added with the target claim generator’s signing key(s). Ability to deliver assets to targeted users.  For example, via publishing to social media or on-path attacks.

====== Impact analysis

An attacker may be able to misuse or exploit a claim signing system to create malicious C2PA manifests. These can then be delivered to targeted users/systems. Note that valid claim signatures will be limited to credentials used by the targeted claim signing system; an attacker cannot impersonate other signers in this scenario.

If the signer’s credential type does not support or provide a means for revocation, it may be necessary to remove the trust anchor associated with the signer’s credential from the respective C2PA trust list to effectively revoke the malicious manifests. In this case, all manifests associated with the trust anchor will be invalidated.

Revocation of the signing key associated with the malicious manifests may invalidate other manifests if signing keys are reused between claim generation / claim signing system  users.

====== Security guidance

Claim generators must adhere to industry best practices for information security and anti-abuse practices, including leveraging available platform-specific features for deployment (e.g.  https://developer.android.com/training/safetynet[Android SafetyNet], https://developer.apple.com/documentation/devicecheck[Apple DeviceCheck]).  Likewise, claim generators should use platform-specific best practices for key storage and management. For example, usage of hardware security modules, key management services), minimizing key reuse, and revoking keys when compromise is suspected. For more information on key management, see the https://csrc.nist.gov/Projects/Key-Management/Key-Management-Guidelines[NIST Key Management Guidelines].

It is highly recommended that all signing credentials include revocation information.

The impact of this threat scenario could be mitigated through use of decoupled manifests, e.g. by making decoupled C2PA manifests available to user agents when a user suspects falsified provenance data.

Use of decoupled manifests can introduce security and privacy issues. See the xref:_content_binding_security[Content binding security section] for more information.

===== Threat: Issuance of claim signing keys to malicious entity

====== Description

An attacker causes a C2PA claim signing key issuer to issue a valid signing key to them. They then use this signing key to add misleading provenance to a C2PA-enabled media asset.

====== Prerequisites

Ability to bypass unspecified processes for obtaining a claim signing key.

====== Impact analysis

An attacker that is able to obtain a legitimate claim signing key can spoof valid C2PA manifests on arbitrary media assets. This applies to both hard and soft bindings. These manifests will pass validation checks. Further, an attacker will be able to continue to generate media assets with spoofed provenance until the compromised credential is revoked, and revocation status is propagated to the targeted users/systems.

It may be necessary to remove the trust anchor associated with the signer’s credential from the respective C2PA trust list to effectively revoke malicious manifests. In this case, all manifests associated with the trust anchor will be invalidated.

====== Security guidance

The C2PA does not currently specify requirements regarding issuance of claim signing keys. It is recommended that these processes be robust against exploitation and misuse. The https://cabforum.org/baseline-requirements/[CAB Forum Baseline Requirements] provide a working example of security requirements for signing credential issuers.

===== Threat: Swapping ingredients

====== Description

An attacker finds a media asset with a C2PA manifest block that includes an ingredient manifest with a signature from valid, non-public credentials. They replace the ingredient manifest with a malicious manifest.

====== Prerequisites

Ability to discover media with susceptible ingredient manifest and generate a malicious replacement. And deliver the media asset to the target users/systems.

====== Impact analysis

Validation of ingredients is optional. See the https://c2pa.org/public-draft/#_validation[Validation section of the C2PA specification] for details.

A ingredient validator that does not have access to the original, non-public signing credential cannot differentiate between the original and compromised provenance. Both ingredient manifests will fail validation. An ingredient validator that does have access to the original signing credential will be able to differentiate between the two C2PA-enabled media assets. The original manifest will validate, and the malicious manifest will fail validation.

====== Security guidance

Validators that apply private address books, and also act as claim generators, can optionally use C2PA reviews (see https://c2pa.org/public-draft/#_use_of_schema_org[Use of Schema.org]) to propagate their assessment of ingredients to downstream consumers. When this validation is peformed on both media assets described in this scenario, downstream consumers will be able to differentiate between them.

===== Threat: Binding malicious media asset to valid provenance via soft-binding collision

====== Description

An attacker generates a malicious media asset whose soft binding matches the soft binding of a legitimate, target media asset. The attacker creates a decoupled, soft-bound manifest for the malicious media asset. The malicious media asset is then delivered to the target/system user, which retrieves the legitimate C2PA manifest via the common soft binding.

====== Prerequisites

Ability to generate a colliding soft binding for a target media asset and publish the resulting manifest such that it will be retrieved by the target user/system for the target media asset.

====== Impact analysis

Malicious media bound to legitimate C2PA provenance data is validated and presented to the target system/user.

====== Security guidance

C2PA provides guidance on applying soft bindings, which may include algorithms for mitigating this type of attack. See the TODO[content binding documentation] for details.

===== Threat: Use valid W3c Verified Credentials to add authenticity to incorrect actor attribution

====== Description

An attacker copies a valid W3C Verified Credential (VC) from an existing C2PA manifest. The attacker then creates a separate, valid C2PA manifest that includes the copied VC, misleading information, and a valid claim signature. The resulting manifest is presented to consumers.

====== Prerequisites

* Ability to copy a valid VC from an existing C2PA manifest
* Ability to generate and sign a claim that passes validation
* Ability to deliver assets to consumer(s), for example via publishing to social media

====== Impact analysis

Consumers are presented with UX that indicates the subject of copied VC is associated with the manipulated asset.

====== Security guidance

User agents must make a clear separation between the signer of the claim's assertions and any included W3C Verifiable Credentials. It must be clear that the association of those VCs to assertions, are made by the claim signer (i.e. the subject of the VC was not responsible for the association).

Claim generators and signing operations should adhere to security best practices.

===== Threat: Binding valid media asset to malicious provenance via soft-binding collision

====== Description

An attacker generates a dummy media asset whose soft binding matches the soft binding of another media asset. They then use a claim generator to create a valid, malicious C2PA claim(s), and a decoupled C2PA manifest. They then publish the C2PA manifest. When the target media asset is validated, the malicious C2PA manifest is retrieved via the common soft binding.

====== Prerequisites

Ability to generate a colliding soft binding for a target media asset and publish the resulting manifest such that it will be retrieved by the target user/system for the target media asset.

====== Impact analysis

Malicious provenance data bound to a legitimate media asset is validated and presented to the target system/user.

====== Security guidance

C2PA provides guidance on applying soft bindings, which may include algorithms for mitigating this type of attack. See the TODO[content binding documentation] for details.

==== Goal: Exploit functionality introduced by C2PA

Threat scenarios in this category do not aim to break the C2PA security model.  Rather, they aim to leverage C2PA functionality to perform systems attacks or exploitation. Note that the set of scenarios included here is not meant to be comprehensive; they focus on application of known exploitation techniques against behavior explicitly referenced in the C2PA specification.

(This section is to be expanded)
