:revdate: {docdate}
:version-label!: 
:sectnums:
:sectnumlevels: 5 
:chapter-label:
:source-highlighter: rouge

## Assertions
### General

It is expected that each of the actors in the system that creates or processes an asset will produce one or more *assertions* about when, where, and how the asset was originated or transformed. An assertion is labelled data, typically (though not required to be) in a CBOR-based structure which represents a declaration made by an actor about an asset. Some of these actors will be human and add human-generated information (e.g., copyright) while other actors are machines (software/hardware) providing the information they generated (e.g., camera type).

Some examples of assertions are:

* Exif information (e.g. camera information such as maker, lens)
* Actions performed on the asset (e.g., clipping, color correction)
* Thumbnail of the asset or its ingredients
* Content bindings (e.g., cryptographic hashes)

Certain assertions may be redacted by subsequent claims (see <<_redaction_of_assertions>>), but they cannot be modified once made as part of a claim.

### Labels

Each assertion has a *label* defined either by the C2PA specifications or an external entity.

Labels are string values organized into namespaces using a period (`.`) as a separator.  The namespace component of the label can be an entity, or a reference to a well-established standard (see ABNF below). The most common labels will be defined by the C2PA and will begin with `c2pa.`. Entity-specific labels shall begin with the Internet domain name for the entity similar to how Java packages are defined (e.g., `com.litware`, `net.fineartschool`). Well-established standards can use the "stds." prefix when describing their namespace.  They are also versioned with a simple incrementing integer scheme (e.g., `c2pa.actions.v2`). If no version is provided, it is considered as `v1`. The list of publicly known labels can be found in <<_c2pa_standard_assertions>>.

[source,abnf]
----
namespaced-label = qualified-namespace label
qualified-namespace = entity / ( "stds."  std-name )
entity = 1*( DIGIT / ALPHA / "-" )
std-name = 1*( DIGIT / ALPHA / "-" )
label = 1*("." 1(ALPHA / "_" ) *( DIGIT / ALPHA / "_" ) )
----

The period-separated components of a label follow the variable naming convention (`[a-zA-Z_][a-zA-Z0-9_]*`) specified in the POSIX or C locale, with the restriction that the use of a repeated underscore character (`__`) is reserved for labeling multiple assertions of the same type.

### Versioning

When an assertion’s schema is changed, it should be done in a backwards-compatible manner. This means that new fields may be added and existing ones may be marked as deprecated (i.e., can be read, but never written). Existing fields shall not be removed. The label would then consist of an incremented version number, for example moving from `c2pa.ingredient` to `c2pa.ingredient.v2`.

Deprecated fields for C2PA standard assertions shall be indicated in <<_c2pa_standard_assertions>>. Tools which enable actors to create assertions shall prevent the actor from inserting data into deprecated assertion fields.

In addition, there are situations where a non-backwards compatible change is required. In that case, instead of increasing the label’s version number, the assertion shall be given a new label. For example, `c2pa.ingredient` could be changed to the fictional `c2pa.component`.

### Multiple Instances

Multiple assertions of the same type can occur in the same manifest, but since assertions are referenced by claims via their label, the assertion labels must be unique.  This is accomplished by adding a double-underscore and and a monotonically increasing index to the label.  For example, if a manifest contains a single assertion of type `stds.schema-org.CreativeWork`, then the assertion label will be `stds.schema-org.CreativeWork`.  If a manifest contains three assertions of this type, the labels will be `stds.schema-org.CreativeWork`, `stds.schema-org.CreativeWork\__1` and `stds.schema-org.CreativeWork__2`.

When a label includes a version number, that version number is part of the label itself. As such, when there are multiple instances, the instance number continues to follow the label - e.g., `c2pa.ingredient.v2__2`.

### Assertion Store

The set of assertions referenced by a xref:_claims[claim] in a manifest are collected together into a logical construct that is referred to as the *assertion store*. The assertions and assertion store shall be stored as described in <<_use_of_jumbf>>; in particular, the assertion store shall be located in the same C2PA Manifest box as the claim that refers to its assertions.

For each manifest, there is a single assertion store associated with it. However, as an asset may have multiple manifests associated with it, each one representing a specific series of assertions, there may be multiple assertion stores associated with an asset.

### Embedded vs Externally-Stored Data

Some assertion data, due to its size or an infrequent need for it, may be externally hosted. Such data are not embedded in the assertion store, but instead are referenced by URI. Unlike embedded assertions, external assertions are not retrieved nor validated as part of manifest validation, and are only retrieved and validated when specifically needed by an application. This is accomplished through a cloud data assertion (see <<_cloud_data>>), and the different validation rules are described in <<_validate_the_assertions>>.

### Redaction of Assertions

Assertions that are present in an asset-embedded manifest may be removed from that asset's manifest when the asset is xref:_ingredient_storage[used as an ingredient]. This process is called redaction.

Redaction involves removing either the entire assertion from the manifest's assertion store or retaining the labeled assertion container but replacing its data with zeros (binary `\0` values). In addition, a record that something was removed must be added to the xref:_claims[claim] in the form of a xref:_uri_references[URI reference] to the redaction assertion in the `redacted_assertions` field of the claim. 

[NOTE]
====
Because each assertion’s xref:_uri_references[URI reference] includes the assertion label, it is also known what type of information (e.g., thumbnail, IPTC metadata, etc.) was removed. This enables both humans and machines to apply rules to determine if the removal was acceptable.
====

Unless the redaction of the assertion also requires modification to the digital content, an xref:_update_manifest[update manifest] shall be used to document the redaction as it makes a statement about the non-changes to the content. 

Claims generators shall not redact assertions with a label of `c2pa.actions` as this assertion type represents essential information in understanding the history of an asset. 
