:revdate: {docdate}
:version-label!: 
:sectnums:
:sectnumlevels: 5 
:chapter-label:
:source-highlighter: rouge

## Unique Identifiers

Every asset that is referenced from the xref:_claims[claim] shall be referenced via a unique identifier. In addition, these identifiers are used in various parts of a C2PA-enabled workflow, such as when identifying it as an xref:_ingredients[ingredient] in a derived or composed asset.

### Using XMP
When an asset contains embedded XMP, that XMP shall include (at least) values for `xmpMM:DocumentID` and `xmpMM:InstanceID` as defined in https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2014-12/XMPSpecificationPart2.pdf[XMP Specification Part 2, 2.2]. If an asset does not contain XMP at the time a claim is made, and the type of the asset supports it, an embedded XMP packet may be created as part of the process, and the identifiers shall be added to it.

.NOTE 1
NOTE: Some asset types are not suited for embedded XMP (e.g., text). It is possible to create XMP as a sidecar.

### Other Identifiers
Instead of using XMP, a unique identifier for an asset could be a URI defined by standards such as https://www.w3.org/TR/did-core/[Decentralized Identifiers (DID)], http://www.handle.net/[Handle], https://www.eidr.org/[EIDR] and https://www.doi.org/[DOI].

Another standard unique identifier for an asset could be the cryptographic hash of the asset. When this method is used, the hash shall be represented using a standard https://tools.ietf.org/html/rfc4122[RFC 4122 UUID] following the recommendations at https://datatracker.ietf.org/doc/html/draft-thiemann-hash-urn-01 .

.EDITORS NOTE
NOTE: Other methods may be defined here as they are developed.


### URI References

Assertions and claims, whether they are stored internally to the asset (ie. embedded) or stored externally to the asset (e.g., in the cloud), shall be referenced via JUMBF URI references as defined in https://www.iso.org/standard/73604.html[ISO 19566-5, C.2]. This URI shall be used as part of a `hashed_uri` data structure:

[source,json]
----
include::../../schemas/json/hashed-uri.json[]
----

Because assertion stores must be located in the same C2PA Manifest box as the claim that refers to them, only `self#jumbf` URIs are permitted. These `self#jumbf` URIs may be relative to the entire C2PA Manifest Store, in which case they shall start with a `/` (U+002F, Slash), or relative to the current manifest. URIs shall not contain the sequence `..` (a pair of U+002E, Full Stop). 

NOTE: Cloud data assertions use a different schema for URIs which is described in <<_cloud_data>>.

**Examples** 

- `self#jumbf=/c2pa/urn:uuid:f095f30e-6cd5-4bf7-8c44-ce8420ca9fb7/c2pa.assertions/c2pa.thumbnail.claim.jpeg` is relative to the entire store (since it starts with `/`), 

- `self#jumbf=c2pa.assertions/c2pa.thumbnail.claim.jpeg` would be relative to the manifest of the box containing the URI.

The hash is performed over the canonical serialization of the assertion data, omitting the surrounding container.  For example, if the assertion type is `c2pa.actions`, then the hash is calculated over the canonical serialization of `actions-map`.
